### ISSUE TITLE
Now this doesn't work completely

### ISSUE THREAD

**Issue by lamrongol** [uakihir0/kbsky#68]
This may be related to #64 , now this library doesn't work completely, for example, `FeedResource` and `RepoStrongRef` and so on are not found. I don't edit any codes as same as previous time.
```
./gradlew build --refresh-dependencies
```
command doesn't work, either.

**Comment by lamrongol** [comment]
I noticed some kbsky classes works and deleted `import`s, I found some classes packages are changed, for example:
old: import work.socialhub.kbsky.api.app.bsky.FeedResource;
now: import work.socialhub.kbsky.api.bsky.FeedResource;

However, why do you do these breaking change?

**Comment by uakihir0** [comment]
すいません。
チャットの対応で、既存のパッケージ構成に無理が発生してしまったため、パッケージの大幅な変更を行いました。SNAPSHOT で運用しているのが問題だと思うので、バージョンを切って対応しようと思います。

--- 


I'm sorry.
The chat response caused an impossibility in the existing package configuration, so we made a major change in the package. we think the problem is that we are operating with SNAPSHOT, so we will cut the version to accommodate the problem.
